import type { Metadata } from "next";
import { ChakraProvider } from "@chakra-ui/provider";
// import { ChakraProvider } from "@chakra-ui/react";でも良いが、bundleqizeが大きくなるので、@chakra-ui/providerを使って軽量化

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <ChakraProvider>{children}</ChakraProvider>
      </body>
    </html>
  );
}
